baseurl = "https://example.org/"
languageCode = "en-us"
title = "Pivotal HDB"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
sectionPagesMenu = "main"


[params]
	# General information
	# Repository

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "deep orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
    name = "Ambari Administration"
    title = "ambari"
    weight = -110
    identifier = "admin"
    url = "/admin/ambari-admin"


[[menu.main]]
	name   = "Pivotal HDB Docs"
	url    = "/"
	weight = 0

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
